// Simple synchronous SRAM with optional init file for simulation
// - Responds in 1 cycle when valid
// - Supports byte writes via wstrb
//Will swap to SRAM generated by SRAM-Forge later
//This module logically works well like an SRAM for sim, but will probably synthezise to a bunch of FF's! :(
module simple_sram #(
    parameter integer WORDS = 1024,
    parameter INIT_HEX = ""
)(
    input  wire        clk,
    input  wire        resetn,

    input  wire        valid,
    output reg         ready,

    input  wire [3:0]  wstrb,
    input  wire [31:0] addr,   // byte address
    input  wire [31:0] wdata,
    output reg  [31:0] rdata
);
    reg [31:0] mem [0:WORDS-1];

    // optional init
    integer i;
    initial begin
        if (INIT_HEX != "") begin
            $display("simple_sram: loading INIT_HEX=%s", INIT_HEX);
            $readmemh(INIT_HEX, mem);
            $display("SRAM[0]=%08x SRAM[1]=%08x SRAM[2]=%08x SRAM[3]=%08x",
         mem[0], mem[1], mem[2], mem[3]);

        end else begin
            // default clear (optional)
            for (i = 0; i < WORDS; i = i + 1)
                mem[i] = 32'h0000_0000;
        end
    end

    wire [31:0] word_index = addr >> 2;

    always @(posedge clk) begin
        if (!resetn) begin
            ready <= 1'b0;
            rdata <= 32'h0;
        end else begin
            ready <= 1'b0;
            if (valid) begin
                ready <= 1'b1;
                rdata <= mem[word_index];

                if (wstrb[0]) mem[word_index][ 7: 0] <= wdata[ 7: 0];
                if (wstrb[1]) mem[word_index][15: 8] <= wdata[15: 8];
                if (wstrb[2]) mem[word_index][23:16] <= wdata[23:16];
                if (wstrb[3]) mem[word_index][31:24] <= wdata[31:24];
            end
        end
    end
endmodule
